name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload artifact to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/final-project-front"
          args: -r
          
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            sudo cp -rf final-project-front/* /var/www/html
            sudo systemctl reload nginx
            sudo rm -r final-project-front/
